#!/usr/bin/env python3
"""Writes Tabor/Core/Districts.swift: the outlines of Warsaw's 18 districts, for the
"Every district" badge (issue #35). Apple's geocoder names a neighbourhood more often than
a district ("Grochów", "Tarchomin"), so the badge places each catch by its coordinates instead.

Outlines come from OpenStreetMap through Nominatim (one request a second, as its usage
policy asks), are simplified to ~5 m and stored as Google-encoded polylines.

    python3 scripts/build_districts.py
"""
import json
import time
import urllib.parse
import urllib.request
from pathlib import Path

DISTRICTS = [
    "Bemowo", "Białołęka", "Bielany", "Mokotów", "Ochota", "Praga-Południe", "Praga-Północ",
    "Rembertów", "Śródmieście", "Targówek", "Ursus", "Ursynów", "Wawer", "Wesoła", "Wilanów",
    "Włochy", "Wola", "Żoliborz",
]
TOLERANCE = 0.00005  # degrees, ~5 m: neighbours' simplified edges stay within a few metres
OUT = Path(__file__).resolve().parent.parent / "Tabor/Core/Districts.swift"


def fetch(name):
    q = urllib.parse.urlencode({"q": f"{name}, Warszawa", "format": "jsonv2", "polygon_geojson": 1, "limit": 5})
    req = urllib.request.Request("https://nominatim.openstreetmap.org/search?" + q,
                                 headers={"User-Agent": "tabor-districts/1.0 (build script)"})
    for r in json.load(urllib.request.urlopen(req, timeout=60)):
        if r.get("type") == "administrative" and r["geojson"]["type"] == "Polygon":
            return r["geojson"]["coordinates"][0]  # outer ring; Warsaw's districts have no holes
    raise SystemExit(f"no outline for {name}")


def simplify(pts, tol):
    """Douglas-Peucker on (lon, lat) pairs."""
    if len(pts) < 3:
        return pts
    (x1, y1), (x2, y2) = pts[0], pts[-1]
    dx, dy = x2 - x1, y2 - y1
    norm = (dx * dx + dy * dy) ** 0.5
    def dist(p):
        if norm == 0:
            return ((p[0] - x1) ** 2 + (p[1] - y1) ** 2) ** 0.5
        return abs(dy * p[0] - dx * p[1] + x2 * y1 - y2 * x1) / norm
    i, d = max(((i, dist(p)) for i, p in enumerate(pts[1:-1], 1)), key=lambda t: t[1])
    if d <= tol:
        return [pts[0], pts[-1]]
    return simplify(pts[:i + 1], tol)[:-1] + simplify(pts[i:], tol)


def encode(pts):
    """Google polyline, latitude first, 1e5 precision (`Polyline.decode` in Routes.swift)."""
    out, plat, plon = [], 0, 0
    for lon, lat in pts:
        ilat, ilon = round(lat * 1e5), round(lon * 1e5)
        for v in (ilat - plat, ilon - plon):
            v = ~(v << 1) if v < 0 else v << 1
            while v >= 0x20:
                out.append(chr((0x20 | (v & 0x1f)) + 63))
                v >>= 5
            out.append(chr(v + 63))
        plat, plon = ilat, ilon
    return "".join(out)


def main():
    lines = []
    for i, name in enumerate(DISTRICTS):
        if i:
            time.sleep(1.1)
        ring = fetch(name)
        # A closed ring's first and last points are the same, which DP can't split on.
        small = simplify(ring[:-1], TOLERANCE) + [ring[0]]
        print(f"{name}: {len(ring)} → {len(small)} points")
        poly = encode(small).replace("\\", "\\\\")
        lines.append(f'        ("{name}", "{poly}"),')
    OUT.write_text(
        "// Generated by scripts/build_districts.py. Don't edit by hand.\n"
        "// District outlines © OpenStreetMap contributors, ODbL (openstreetmap.org/copyright).\n\n"
        "extension Districts {\n"
        "    static let encoded: [(name: String, polyline: String)] = [\n"
        + "\n".join(lines) + "\n    ]\n}\n")
    print(f"wrote {OUT}")


if __name__ == "__main__":
    main()
